import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Header from "./header";
const inter = Roboto({ subsets: ["latin"], weight: ['100', '300', '400', '500', '700', '900'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="max-w-4xl mx-auto p-4">
        <Header></Header>
          {children}
        </main>
      </body>
    </html>
  );
}
